### ISSUE TITLE
麻烦问下b450m 不解锁cfg可以安装bigsur吗？

### ISSUE THREAD

**Issue by EligeY** [ngaaron/msi-b450m-mortar-Hackintosh-bigsur#2]
麻烦问下b450m 不解锁cfg可以安装bigsur吗？

配置 b450m 3600 rx580,用您这个efi可以吗?

**Comment by 2535688890** [comment]
我的配置跟你的一模一样，Catalina 升级Big Sur，重启安装是失败的，提示EB[] ，在网上查了下应该是因为CFG的问题，目前无法正常升级

**Comment by ghost** [comment]
[EB|#LOG:EXITBS:START]

> 我的配置跟你的一模一样，Catalina升级Big Sur，重启安装是失败的，提示EB []，在网上查了下应该是因为CFG的问题，目前无法正常升级

[EB|#LOG:EXITBS:START]吗？  我也是  看网上解决办法都是解锁cfg  但是b450没找到解锁办法

**Comment by 2535688890** [comment]
> [EB|#LOG:EXITBS:START]
> 
> > 我的配置跟你的一模一样，Catalina升级Big Sur，重启安装是失败的，提示EB []，在网上查了下应该是因为CFG的问题，目前无法正常升级
> 
> [EB|#LOG:EXITBS:START]吗？  我也是  看网上解决办法都是解锁cfg  但是b450没找到解锁办法
> 

是的

**Comment by 2535688890** [comment]
据说有github上有项目可以安装了，这两天试试看

**Comment by ghost** [comment]
> 据说有github上有项目可以安装了，这两天试试看

https://github.com/Whosydd/MSI-B450m-Hackintosh-BigSur  可以试下这个

**Comment by EligeY** [comment]
https://github.com/Tyrone2333/r5-2600-b450m-bazooka-5700-hackintosh  这个版本efi完美解决
